from app.models import Book

INITIAL_BOOKS = [
    # Harry Potter Series
    Book(
        id=1,
        title="Harry Potter and the Philosopher's Stone",
        author="J.K. Rowling",
        genre="Fantasy",
        description="An orphaned boy discovers he's a wizard and begins his magical education at Hogwarts School of Witchcraft and Wizardry.",
        image_url="/images/הארי פוטר 1 ואבן החכמים.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=2,
        title="Harry Potter and the Chamber of Secrets",
        author="J.K. Rowling",
        genre="Fantasy",
        description="Harry returns to Hogwarts for his second year and uncovers dark secrets within the school.",
        image_url="/images/הארי פוטר 2 וחדר הסודות.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=3,
        title="Harry Potter and the Prisoner of Azkaban",
        author="J.K. Rowling",
        genre="Fantasy",
        description="A dangerous prisoner escapes from Azkaban, and Harry discovers truths about his past.",
        image_url="/images/הארי פוטר 3 והאסיר מאזקבאן.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=4,
        title="Harry Potter and the Goblet of Fire",
        author="J.K. Rowling",
        genre="Fantasy",
        description="Harry competes in the dangerous Triwizard Tournament and faces deadly challenges.",
        image_url="/images/הארי פוטר 4 וגביע האש.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=5,
        title="Harry Potter and the Order of the Phoenix",
        author="J.K. Rowling",
        genre="Fantasy",
        description="Harry forms a secret organization to learn Defense Against the Dark Arts.",
        image_url="/images/הארי פוטר 5 ומסדר עוף החול.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=6,
        title="Harry Potter and the Half-Blood Prince",
        author="J.K. Rowling",
        genre="Fantasy",
        description="Harry learns about Voldemort's past and prepares for the final battle.",
        image_url="/images/הארי פוטר 6 והנסיך חצוי הדם.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=7,
        title="Harry Potter and the Deathly Hallows",
        author="J.K. Rowling",
        genre="Fantasy",
        description="Harry, Ron, and Hermione embark on a dangerous quest to destroy Voldemort's Horcruxes.",
        image_url="/images/הארי פוטר 7 ואוצרות המוות.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    
    # Kristin Harmel Books
    Book(
        id=8,
        title="The Paris Daughter",
        author="Kristin Harmel",
        genre="Historical Fiction",
        description="A gripping story of two mothers in Nazi-occupied Paris who must make impossible choices to save their daughters.",
        image_url="/images/הבת מפריז קריסטין הרמל.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=9,
        title="The Art of French Kissing",
        author="Kristin Harmel",
        genre="Romance",
        description="A baker discovers her grandmother's past and embarks on a journey to France to uncover family secrets.",
        image_url="/images/נשיקה צרפתית קריסטין הרמל.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=10,
        title="The Book of Lost Names",
        author="Kristin Harmel",
        genre="Historical Fiction",
        description="A young woman forges documents to save Jewish children during WWII, creating a secret book of their true identities.",
        image_url="/images/ספר השמות האבודים קריסטין הרמל.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=11,
        title="Italian for Beginners",
        author="Kristin Harmel",
        genre="Fiction",
        description="A woman wakes up in an alternate reality where her life took a different path.",
        image_url="/images/איטלקית למתחילים קריסטין הרמל.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=12,
        title="The Room on Rue Amélie",
        author="Kristin Harmel",
        genre="Historical Fiction",
        description="An American woman in Paris helps Allied pilots escape Nazi-occupied France.",
        image_url="/images/הדירה ברחוב אמלי קריסטין הרמל.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=13,
        title="How to Save a Life",
        author="Kristin Harmel",
        genre="Historical Fiction",
        description="A woman raised in the wilderness must teach Jewish refugees to survive in the forest during WWII.",
        image_url="/images/רק עוד יום אחד קריסטין הרמל.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    
    # Other Books
    Book(
        id=14,
        title="The Lost Letter",
        author="Alyson Richman",
        genre="Historical Fiction",
        description="A stamp dealer discovers a lost letter that leads her to uncover a World War II love story.",
        image_url="/images/גן המכתבים אליסון ריצמן.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=15,
        title="The Star-Crossed Sisters of Tuscany",
        author="Lori Nelson Spielman",
        genre="Romance",
        description="A young woman embarks on a journey through Italy to break a family curse with her great-aunt.",
        image_url="/images/הזכות לאהוב לורי נלסון ספילמן.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=16,
        title="The Secret of Snow",
        author="Ann Rinaldi",
        genre="Historical Fiction",
        description="A young girl's journey through colonial America during the Revolutionary War.",
        image_url="/images/פנינה בשלג אן רוז.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    
    # David Baldacci Series
    Book(
        id=17,
        title="One Summer",
        author="David Baldacci",
        genre="Thriller",
        description="A man given months to live receives a miraculous cure and must rebuild his shattered family.",
        image_url="/images/מטען חורג דיוויד.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=18,
        title="The Sixth Man",
        author="David Baldacci",
        genre="Thriller",
        description="A brilliant mathematician is accused of murder, and two investigators must uncover the truth.",
        image_url="/images/האיש השישי דיוויד.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=19,
        title="The First Family",
        author="David Baldacci",
        genre="Thriller",
        description="When the First Family is threatened, a Secret Service agent must protect them at all costs.",
        image_url="/images/המשפחה הראשונה דיוויד.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=20,
        title="Simple Genius",
        author="David Baldacci",
        genre="Thriller",
        description="A detective investigates mysterious deaths at a CIA think tank.",
        image_url="/images/גאון פשוט דיוויד.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=21,
        title="Split Second",
        author="David Baldacci",
        genre="Thriller",
        description="Two Secret Service agents must solve a complex mystery that threatens national security.",
        image_url="/images/שבריר שניה דיוויד.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=22,
        title="Hour Game",
        author="David Baldacci",
        genre="Thriller",
        description="A serial killer mimics famous murders, and investigators race against time to stop them.",
        image_url="/images/משחק השעות דיוויד.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    
    # Additional Popular Books
    Book(
        id=23,
        title="It Ends with Us",
        author="Colleen Hoover",
        genre="Romance",
        description="A woman must choose between the love of her life and breaking painful cycles from the past.",
        image_url="/images/It Ends with Us.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=24,
        title="Pride and Prejudice",
        author="Jane Austen",
        genre="Romance",
        description="The timeless story of Elizabeth Bennet and Mr. Darcy navigating love and society in Regency England.",
        image_url="/images/Pride and Prejudice Jane Austen.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=25,
        title="The Book Thief",
        author="Markus Zusak",
        genre="Historical Fiction",
        description="Death narrates the story of a young girl who steals books during Nazi Germany.",
        image_url="/images/The Book Thief Markus Zusak.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=26,
        title="The Da Vinci Code",
        author="Dan Brown",
        genre="Thriller",
        description="A symbologist races through Europe solving ancient riddles to uncover a secret that could shake Christianity.",
        image_url="/images/The Da Vinci Code Dan Brown.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=27,
        title="Gone Girl",
        author="Gillian Flynn",
        genre="Thriller",
        description="A woman disappears on her anniversary, and her husband becomes the prime suspect in this twisted psychological thriller.",
        image_url="/images/Gone Girl Gillian Flynn.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    
    # Children's Books
    Book(
        id=28,
        title="A House for Rent",
        author="Leah Goldberg",
        genre="Children",
        description="A charming children's story about finding the perfect home.",
        image_url="/images/דירה להשכיר.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=29,
        title="Yael's House",
        author="Various",
        genre="Children",
        description="A delightful story about a special house.",
        image_url="/images/הבית של יעל.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=30,
        title="The Lion Who Loved Strawberries",
        author="Various",
        genre="Children",
        description="A sweet story about a lion with an unusual favorite food.",
        image_url="/images/האריה שאהב תות.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=31,
        title="Monkey Has a Problem",
        author="Various",
        genre="Children",
        description="A funny tale about a monkey trying to solve a tricky problem.",
        image_url="/images/לקוף יש בעיה.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=32,
        title="Raspberry Juice",
        author="Various",
        genre="Children",
        description="A colorful story about sharing and friendship.",
        image_url="/images/מיץ פטל.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=33,
        title="Corn Hef",
        author="Various",
        genre="Children",
        description="An imaginative tale featuring corn adventures.",
        image_url="/images/תירס חפ.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=34,
        title="Eliezer and the Carrot",
        author="Various",
        genre="Children",
        description="A delightful story about a boy and his special carrot.",
        image_url="/images/אליעזר והגזר.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=35,
        title="The Very Hungry Caterpillar",
        author="Eric Carle",
        genre="Children",
        description="A beloved classic about a caterpillar's transformation into a butterfly.",
        image_url="/images/הזחל הרעב.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=36,
        title="Where is Pluto?",
        author="Various",
        genre="Children",
        description="A search adventure for the beloved planet.",
        image_url="/images/איה פלוטו.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
    Book(
        id=37,
        title="The Giving Tree",
        author="Shel Silverstein",
        genre="Children",
        description="A timeless tale of unconditional love and generosity.",
        image_url="/images/העץ הנדיב.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[],
        borrowed_by=[]
    ),
]