from app.models import Book

INITIAL_BOOKS = [
   Book(
        id=1,
        title="The Midnight Library",
        author="Matt Haig",
        genre="Fiction",
        description="Between life and death, a library contains infinite books with infinite lives. Nora must choose which life she wants to truly live.",
        image_url="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1602190253i/52578297.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[]
    ),
    Book(
        id=2,
        title="It Ends with Us",
        author="Colleen Hoover",
        genre="Romance",
        description="A woman must choose between the love of her life and the painful patterns of the past in this emotional story about breaking cycles.",
        image_url="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1470427482i/27362503.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[]
    ),
    Book(
        id=3,
        title="The Silent Patient",
        author="Alex Michaelides",
        genre="Thriller",
        description="A famous painter shoots her husband and then never speaks again. A psychotherapist becomes obsessed with uncovering her motive.",
        image_url="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1582759969i/40097951.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[]
    ),
    Book(
        id=4,
        title="Educated",
        author="Tara Westover",
        genre="Biography",
        description="A woman who grew up in a survivalist family with no formal education goes on to earn a PhD from Cambridge University.",
        image_url="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1506026635i/35133922.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[]
    ),
    # שאר הספרים נשארים אותו דבר...
    Book(
        id=5,
        title="Harry Potter and the Philosopher's Stone",
        author="J.K. Rowling",
        genre="Fantasy",
        description="An orphaned boy discovers he's a wizard and embarks on magical adventures at Hogwarts School of Witchcraft and Wizardry.",
        image_url="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1474154022i/3.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[]
    ),
    Book(
        id=6,
        title="The Hobbit",
        author="J.R.R. Tolkien",
        genre="Fantasy",
        description="Bilbo Baggins, a reluctant hero, joins a quest to reclaim a treasure guarded by the dragon Smaug in this timeless adventure.",
        image_url="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546071216i/5907.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[]
    ),
    Book(
        id=7,
        title="Pride and Prejudice",
        author="Jane Austen",
        genre="Romance",
        description="The timeless story of Elizabeth Bennet and Mr. Darcy, navigating love, class, and first impressions in Regency England.",
        image_url="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1320399351i/1885.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[]
    ),
    Book(
        id=8,
        title="1984",
        author="George Orwell",
        genre="Dystopian",
        description="A chilling vision of a totalitarian future where Big Brother watches everything and independent thought is a crime.",
        image_url="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1657781256i/61439040.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[]
    ),
    Book(
        id=9,
        title="To Kill a Mockingbird",
        author="Harper Lee",
        genre="Fiction",
        description="A young girl in Depression-era Alabama witnesses her father defending a Black man falsely accused of a terrible crime.",
        image_url="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1553383690i/2657.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[]
    ),
    Book(
        id=10,
        title="The Kite Runner",
        author="Khaled Hosseini",
        genre="Fiction",
        description="A powerful story of friendship, betrayal, and redemption set against Afghanistan's tumultuous history.",
        image_url="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1579036753i/77203.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[]
    ),
    Book(
        id=11,
        title="The Book Thief",
        author="Markus Zusak",
        genre="Historical Fiction",
        description="Death narrates the story of a young girl who steals books and shares them during Nazi Germany, finding solace in words.",
        image_url="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1522157426i/19063.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[]
    ),
    Book(
        id=12,
        title="Where the Crawdads Sing",
        author="Delia Owens",
        genre="Mystery",
        description="A mysterious girl raised in the marshes becomes the prime suspect in a murder investigation in this mesmerizing tale.",
        image_url="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1582135294i/36809135.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[]
    ),
    Book(
        id=13,
        title="The Da Vinci Code",
        author="Dan Brown",
        genre="Thriller",
        description="A symbologist races through Europe solving ancient riddles to uncover a secret that could shake Christianity's foundations.",
        image_url="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1579621267i/968.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[]
    ),
    Book(
        id=14,
        title="Gone Girl",
        author="Gillian Flynn",
        genre="Thriller",
        description="A woman disappears on her anniversary, and her husband becomes the prime suspect in this twisted psychological thriller.",
        image_url="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1554086139i/19288043.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[]
    ),
    Book(
        id=15,
        title="The Martian",
        author="Andy Weir",
        genre="Science Fiction",
        description="An astronaut stranded on Mars must use his ingenuity and humor to survive against impossible odds until rescue arrives.",
        image_url="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1413706054i/18007564.jpg",
        average_rating=0.0,
        total_ratings=0,
        user_ratings={},
        favorites=[]
    ),
]